# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
# IP: The module: 'DCM_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
# IP: The module: 'DCM_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
