# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.cache/wt [current_project]
set_property parent.project_path E:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/3200102346/lab19_MusicPlayer/src/AudioInterface.v
  E:/3200102346/lab19_MusicPlayer/src/button_process_unit.v
  E:/3200102346/lab19_MusicPlayer/src/counter_n.v
  E:/3200102346/lab19_MusicPlayer/src/dds.v
  E:/3200102346/lab19_MusicPlayer/src/dffre.v
  E:/3200102346/lab19_MusicPlayer/src/frequency_rom.v
  E:/3200102346/lab19_MusicPlayer/src/full_adder_n.v
  E:/3200102346/lab19_MusicPlayer/src/mcu.v
  E:/3200102346/lab19_MusicPlayer/src/music_player.v
  E:/3200102346/lab19_MusicPlayer/src/note_player.v
  E:/3200102346/lab19_MusicPlayer/src/simul.v
  E:/3200102346/lab19_MusicPlayer/src/sine_rom.v
  E:/3200102346/lab19_MusicPlayer/src/song_reader.v
  E:/3200102346/lab19_MusicPlayer/src/song_rom.v
  E:/3200102346/lab19_MusicPlayer/src/timer.v
  E:/3200102346/lab19_MusicPlayer/src/MusicPlayerTop.v
}
read_ip -quiet e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
set_property used_in_implementation false [get_files -all e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc]
set_property used_in_implementation false [get_files -all e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc]
set_property used_in_implementation false [get_files -all e:/3200102346/lab19_MusicPlayer/vivado/Music_player/Music_player.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc]

read_edif E:/3200102346/lab19_MusicPlayer/src/AudioInterface.edf
read_edif E:/3200102346/lab19_MusicPlayer/src/button_process_unit.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/3200102346/lab19_MusicPlayer/src/music_player.xdc
set_property used_in_implementation false [get_files E:/3200102346/lab19_MusicPlayer/src/music_player.xdc]


synth_design -top MusicPLayerTop -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MusicPLayerTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MusicPLayerTop_utilization_synth.rpt -pb MusicPLayerTop_utilization_synth.pb"
